# Activity 8: Grouping and Aggregating Data

In this activity, you'll practice using functions to group data and obtain descriptive statistics.

## Submitting this activity:
1. Complete the required challenges and questions
2. Download the file as a Jupyter Notebook by clicking File -> Download -> Download .ipynb
3. Rename the file into the following format: YOURID_Classwork8.ipynb
4. Upload the file into the appropriate place in Canvas

Run the cell below at least once to activate the auto-grader.

In [1]:
!git clone https://github.com/GzzDany/ADIAclasswork.git

from ADIAclasswork.autograde_act7 import *

"git" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

In [2]:
### Import the pandas module with its standard alias pd:
import pandas as pd

### Load the dataset:
df = load_data()

### Visualize the first 5 rows of the dataset:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,congestion_surcharge,Airport_fee,trip_distance_km,tip_percentage,trip_duration,hour_start,weekday,average_speed,length_category,time_of_day
0,2,2024-01-02 17:28:20,2024-01-02 17:35:52,1.0,0.67,1.0,N,163,48,2.0,...,2.5,0.00,1.078258,0.000000,7.533333,17,Tuesday,8.587894,short,afternoon
1,2,2024-01-07 11:53:01,2024-01-07 12:18:55,1.0,10.06,1.0,N,138,230,1.0,...,2.5,1.75,16.189960,34.602410,25.900000,11,Sunday,37.505700,long,morning
2,2,2024-01-15 09:43:32,2024-01-15 09:55:14,6.0,1.57,1.0,N,186,161,1.0,...,2.5,0.00,2.526664,26.611570,11.700000,9,Monday,12.957250,short,morning
3,2,2024-01-31 02:41:03,2024-01-31 02:55:09,1.0,3.81,1.0,N,230,146,1.0,...,2.5,0.00,6.131585,31.570681,14.100000,2,Wednesday,26.091853,long,late night
4,2,2024-01-02 18:10:11,2024-01-02 18:17:01,2.0,1.02,1.0,N,163,162,1.0,...,2.5,0.00,1.641527,35.116279,6.833333,18,Tuesday,14.413406,short,afternoon

## Part 1:

Read the following questions and create a grouped DataFrame that will allow you to answer all of them at once.
1. What was the amount of passengers with the highest average trip duration? Store your result in a variable called "passenger_count_with_highest_mean_duration"
2. What was that highest average trip duration from Question 1? Store your answer in a variable called "passenger_count_highest_mean_duration"
3. What was the number of passengers with the largest mean fare amount? Store your answer in a variable called "passenger_count_with_highest_fare_mean"

In [7]:
df.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee',
       'trip_distance_km', 'tip_percentage', 'trip_duration', 'hour_start',
       'weekday', 'average_speed', 'length_category', 'time_of_day'],
      dtype='str')

In [22]:
### YOUR CODE HERE
g_df = df.groupby("passenger_count").agg(fare_amount = ("fare_amount", "mean"),
                                         avg_duration =("trip_duration", "mean"))

g_df

                 fare_amount  avg_duration
passenger_count
1.0                17.887507     15.585020
2.0                20.737067     16.771425
3.0                20.309893     16.899005
4.0                22.817165     17.749741
5.0                18.195353     16.906411
6.0                17.325271     21.046109
8.0                97.000000      0.050000

In [25]:
### YOUR ANSWERS HERE

passenger_count_with_highest_mean_duration = g_df["avg_duration"].idxmax() 
passenger_count_highest_mean_duration = 21.046109
passenger_count_with_highest_fare_mean = 8

In [26]:
### Autograder cell
### DO NOT MODIFY OR DELETE

grade_p1(globals())

Great! Your answer for 6.0 is correct!
Great! Your answer for 21.046109 is correct!
Great! Your answer for 8 is correct!

## Part 2:

Let's practice with another grouping exercise. Read the following questions and generate a grouped DataFrame that will answer all of them at once:

1. How many trips did the company with ID 1 make? Store your answer in a variable called "total_trips_vendor_1"
2. How much did the company wiht ID 2 make from fares? In other words, what was the total fare amount charged by company 2? Store your answer in a variable called "total_fare_vendor_2"
3. Which vendor had the highest standard deviation in their fare amount? Store your answer in the variable "highest_var_vendor"

<b>Hint:</b> Think about which aggregating function you'll need for each one. They're not the same!

In [14]:
### YOUR CODE HERE
g_df = df.groupby("VendorID").agg(total_fare = ("fare_amount", "sum"),
                                highest_deviation=("fare_amount", "max"),
                                total_trips = ("VendorID", "count"))

g_df

          total_fare  highest_deviation  total_trips
VendorID
1          414035.81              275.5        23757
2         1432182.70              457.0        76243

In [15]:
### YOUR ANSWERS HERE

total_trips_vendor1 = 23757
total_fare_vendor2 = 1432182.70
highest_var_vendor = 2

In [16]:
### Autograder cell
### DO NOT MODIFY OR DELETE

grade_p2(globals())

Great! Your answer for 23757 is correct!
Great! Your answer for 1432182.7 is correct!
Great! Your answer for 2 is correct!

## Part 3:

Let's now try to group the data according to two variables: First, the day of the week and then the hour where the trip started to try to ascertain patterns in the data.

Answer the question: What hour was had the highest demand on Friday? Store your answer in a variable called "friday_most_frequent_answer"

<b>Hint:</b> remember the .max() method after selecting the "Friday" rows using
```
df.loc["Friday"]
```

In [35]:
### YOUR CODE HERE
g_df = df.groupby(["weekday", "hour_start"]).agg(total_fare = ("fare_amount", "count"))

g_df.loc["Friday"]

            total_fare
hour_start
0                  310
1                  184
2                   88
3                   63
4                   39
5                   87
6                  183
7                  441
8                  601
9                  569
10                 689
11                 727
12                 715
13                 723
14                 856
15                 882
16                 838
17                 951
18                1026
19                 888
20                 739
21                 750
22                 805
23                 681

In [36]:
### YOUR ANSWER HERE

friday_most_frequent_hour = 18 ### REPLACE THIS WITH YOUR ANSWER

In [37]:
### Autograder cell
### DO NOT MODIFY OR DELETE

grade_p3(globals())

Great! Your answer for 18 is correct!

Let's use the previous exercise in a different way. Now answer the question: How many trips were carried out on Friday at 22h? Store your answer in a variable called "trips_friday_22"

<b>Hint:</b> You may want to recall the .loc method to access the information you need. You'll have to work with a multi-level index, which is done in the following way:

```
df.loc[(IND_LVL0, IND_LVL1), COL_NAME]
```

In [ ]:
### YOUR CODE HERE

In [38]:
### YOUR ANSWER HERE

trips_friday_22 = 805 ### REPLACE THIS WITH YOUR ANSWER

Let's review filtering! Confirm your previous answer using filtering techniques (creating a Boolean mask and adding, or using .shape) to count how many trips were started on Friday at 22h!

In [ ]:
### YOUR CODE HERE

In [39]:
### Autograder cell
### DO NOT MODIFY OR DELETE

grade_p4(globals())

Great! Your answer for 805 is correct!

## Part 4

Now, let's analyze patterns by weekday and passenger counts.

Answer the following question: In what day of the week did 6-passenger trips occur the most?

<b>Hint:</b> You'll need to group the data by passenger count and weekday, and aggregate using "count", then use .loc to find the passenger_count data for 6 passengers.

Store your answer in a variable called "passenger_count_6_weekday"

In [47]:
### YOUR CODE HERE
g_df = df.groupby(["weekday", "passenger_count"]).agg(total_fare = ("fare_amount", "count"))

g_df

                           total_fare
weekday   passenger_count
Friday    1.0                   10803
          2.0                    2057
          3.0                     436
          4.0                     251
          5.0                     163
          6.0                     125
Monday    1.0                   10581
          2.0                    1970
          3.0                     430
          4.0                     285
          5.0                     173
          6.0                      97
Saturday  1.0                   10116
          2.0                    2617
          3.0                     653
          4.0                     361
          5.0                     170
          6.0                     118
Sunday    1.0                    8371
          2.0                    2042
          3.0                     515
          4.0                     267
          5.0                     146
          6.0                     108
          8.0                       1
Thursday  1.0                   12295
          2.0                    1733
          3.0                     406
          4.0                     198
          5.0                     166
          6.0                     120
Tuesday   1.0                   12718
          2.0                    1848
          3.0                     416
          4.0                     202
          5.0                     174
          6.0                     131
Wednesday 1.0                   13765
          2.0                    2007
          3.0                     428
          4.0                     235
          5.0                     170
          6.0                     132

In [42]:
### YOUR ANSWER HERE

passenger_count_6_weekday = "Wednesday" ### REPLACE THIS WITH YOUR ANSWER

In [43]:
### Autograder cell
### DO NOT MODIFY OR DELETE

grade_p5(globals())

Great! Your answer for Wednesday is correct!