In [51]:
import pandas as pd
import numpy as np

df = pd.read_csv("sales_data_types.csv")
df.head()

,Customer Number,Customer Name,2016,2017,Percent Growth,Jan Units,Month,Day,Year,Active
0,10002,Quest Industries,"$125,000.00","$162,500.00",30.00%,500,1,10,2015,Y
1,552278,Smith Plumbing,"$920,000.00","$1,012,000.00",10.00%,700,6,15,2014,Y
2,23477,ACME Industrial,"$50,000.00","$62,500.00",25.00%,125,3,29,2016,Y
3,24900,Brekke LTD,"$350,000.00","$490,000.00",4.00%,75,10,27,2015,Y
4,651029,Harbor Co,"$15,000.00","$12,750.00",-15.00%,Closed,2,2,2014,N

In [52]:
df.columns = df.columns.str.strip().str.replace(" ", "_").str.lower()
df.columns

Index(['customer_number', 'customer_name', '2016', '2017', 'percent_growth',
       'jan_units', 'month', 'day', 'year', 'active'],
      dtype='str')

In [53]:
df.dtypes

customer_number    int64
customer_name        str
2016                 str
2017                 str
percent_growth       str
jan_units            str
month              int64
day                int64
year               int64
active               str
dtype: object

In [54]:
df["2016"] + df["2017"]

0      $125,000.00 $162,500.00
1    $920,000.00 $1,012,000.00
2        $50,000.00 $62,500.00
3      $350,000.00 $490,000.00
4        $15,000.00 $12,750.00
dtype: str

In [55]:
print("""We got the resulting sales for that year, but with the values stored as string, giving us the data as dtype str. We also have the issue where conversion fails and becomes NaN
We fix this by converting the data to the appropiate type, being float, with careful steps to avoid any issues in conversion""")

We got the resulting sales for that year, but with the values stored as string, giving us the data as dtype str. We also have the issue where conversion fails and becomes NaN
We fix this by converting the data to the appropiate type, being float, with careful steps to avoid any issues in conversion

In [60]:
columns_float = ["2016", "2017", "percent_growth", "jan_units"]
columns_boolean = ["active"]

for col in columns_float:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace(r"[^0-9.]", "", regex=True)  # remove $, commas, spaces, etc.
    )
    
    df[col] = pd.to_numeric(df[col], errors="coerce")

for column in columns_boolean: 
  df[column] = df[column].astype(bool)

df.dtypes

customer_number      int64
customer_name       string
2016               float64
2017               float64
percent_growth     float64
jan_units          float64
month                int64
day                  int64
year                 int64
active                bool
dtype: object

In [61]:
df["start_date"] = pd.to_datetime(df[["year", "month", "day"]])

df["start_date"]

0   2015-01-10
1   2014-06-15
2   2016-03-29
3   2015-10-27
4   2014-02-02
Name: start_date, dtype: datetime64[us]

In [62]:
df.head(3)

,customer_number,customer_name,2016,2017,percent_growth,jan_units,month,day,year,active,start_date
0,10002,Quest Industries,125000.0,162500.0,30.0,500.0,1,10,2015,True,2015-01-10
1,552278,Smith Plumbing,920000.0,1012000.0,10.0,700.0,6,15,2014,True,2014-06-15
2,23477,ACME Industrial,50000.0,62500.0,25.0,125.0,3,29,2016,True,2016-03-29

In [63]:
df.iloc[1:3, 0:2]

   customer_number    customer_name
1           552278   Smith Plumbing
2            23477  ACME Industrial

In [64]:
df_sorted = df.sort_values(by="2016", ascending=True)
df_sorted

,customer_number,customer_name,2016,2017,percent_growth,jan_units,month,day,year,active,start_date
4,651029,Harbor Co,15000.0,12750.0,15.0,NaN,2,2,2014,True,2014-02-02
2,23477,ACME Industrial,50000.0,62500.0,25.0,125.0,3,29,2016,True,2016-03-29
0,10002,Quest Industries,125000.0,162500.0,30.0,500.0,1,10,2015,True,2015-01-10
3,24900,Brekke LTD,350000.0,490000.0,4.0,75.0,10,27,2015,True,2015-10-27
1,552278,Smith Plumbing,920000.0,1012000.0,10.0,700.0,6,15,2014,True,2014-06-15

In [65]:
df["2016"].mean()

np.float64(292000.0)

In [66]:
df.describe()

,customer_number,2016,2017,percent_growth,jan_units,month,day,year,start_date
count,5.000000,5.000000,5.000000e+00,5.00000,4.000000,5.000000,5.000000,5.00000,5
mean,252337.200000,292000.000000,3.479500e+05,16.80000,350.000000,4.400000,16.600000,2014.80000,2015-02-15 14:24:00
min,10002.000000,15000.000000,1.275000e+04,4.00000,75.000000,1.000000,2.000000,2014.00000,2014-02-02 00:00:00
25%,23477.000000,50000.000000,6.250000e+04,10.00000,112.500000,2.000000,10.000000,2014.00000,2014-06-15 00:00:00
50%,24900.000000,125000.000000,1.625000e+05,15.00000,312.500000,3.000000,15.000000,2015.00000,2015-01-10 00:00:00
75%,552278.000000,350000.000000,4.900000e+05,25.00000,550.000000,6.000000,27.000000,2015.00000,2015-10-27 00:00:00
max,651029.000000,920000.000000,1.012000e+06,30.00000,700.000000,10.000000,29.000000,2016.00000,2016-03-29 00:00:00
std,320838.999788,374476.300986,4.151425e+05,10.66302,300.693643,3.646917,11.414903,0.83666,NaN